### ISSUE TITLE
Add arrows to bezier curves

### ISSUE THREAD

**Issue by lecarrera-tec** [johannes-wolf/typst-canvas#49] opened 2023-05-25 22:35 UTC
I already have the code to add arrows to bezier curves. It was almost a copy paste of the code for add arrows to lines. It uses the control points, so the arrows gets the right direction.

My doubt is that I would like to fill the arrows, but I can't, because if I use fill previously, it will fill also the interior of the bezier curve.

**Comment by lecarrera-tec** [comment] 2023-05-25 23:54
Well, I fixed the problem creating a temporary context. If any arrow where enabled, then disabled the fill in the temporary context and use it to construct the bezier. In that way, the fill could be customized for only the arrows. If not arrow is desired, then the fill will be shown in the bezier. Do you think is a good idea?

**Comment by johannes-wolf** [comment] 2023-05-26 11:41
I think we could add a special `mark-fill` to the context which defaults to `black`, what do you think? Because most of the times you want a single fill color for all arrows, not affected by the fill color of other draw commands.

**Comment by lecarrera-tec** [comment] 2023-05-26 13:13
The mark-fill seems a very good idea. Is it possible to make the color of the context stroke the default fill? For me, it would be what I like. And the mark-fill would allow me to set the fill to none.

Mmmm. But what happens if the user set a different color for the mark-fill?, It means that the user wants the full arrow in another color? Because I think I would prefer the arrow of just one color, and not the color of the fill different from the color of the stroke.

**Comment by johannes-wolf** [comment] 2023-05-26 13:42
Then maybe provide `mark-paint`, which accepts a paint that is set as stroke and fill color?
The problem is, that typst does not support setting just the paint of a stroke, so we would need to parse the current stroke using regexp+repr until the PR that brings the needed fields gets merged.

**Comment by johannes-wolf** [comment] 2023-06-07 13:19
Solved by #57.

**Comment by fenjalien** [comment] 2023-06-09 13:22
Um #57 does not add this, it would just allow it to be added without any changes to the function parameters.

**Comment by johannes-wolf** [comment] 2023-06-11 00:15
I have pushed PR #65 which adds marks to *all* kinds of paths:
Syntax:
`place-marks(<path>, <list-of-marks>)`

Example:
```
place-marks(bezier((0,0), (1,0), (.5, 1)), (mark: ">", pos: 1), (mark: "|", pos: .5))
````

See the PR test reference picture for more examples.

@fenjalien @lecarrera-tec Should I also add the mark arguments to the bezier function?

**Comment by johannes-wolf** [comment] 2023-06-27 15:13
I am closing this, as `place-marks` got merged.

**Closed by johannes-wolf** 2023-06-27 15:13 UTC
Labels: bug :bug:, enhancement
